### ISSUE TITLE
用于tableview 展示, icon 不会刷新

### ISSUE THREAD

**Issue by ftxbird** [decemberLi/WQGameIconLabel#1]
该label 用于tableview展示  , 会有重用问题.

**Comment by ftxbird** [comment]
在 该方法  -(void)addIconURLs:(NSArray<NSString *> *)urls withIconSize:(CGSize)iconSize
前 加入 以下代码, 可以暂时解决该问题. 
    for (int i=0; i<self.icons.count; i++) {
        UIView *item = self.icons[i];
        [item removeFromSuperview];
    }

**Comment by decemberLi** [comment]
嗯。写的时候完全没有考虑重用的问题。谢谢提醒。马上去修改这个bug
